spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop  #?? ?? ??
      format_sql: true
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        default_batch_size: 100
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:test;mode=mysql
      username: sa
      password: